name: Check ubuntu-latest-m resources

on:
  push:

jobs:
  report:
    name: Report runner resources (ubuntu-latest-m)
    runs-on: ubuntu-latest-m

    steps:
      - name: System info
        run: |
          uname -a
          cat /etc/os-release
          lscpu
          free -h
          df -h
